baseurl = "https://dschrempf.github.io/"
title = "Concept → IO ()"

languageCode = "en-us"
disqusShortname = ""
MetaDataFormat = "toml"

theme = "skeria"
paginate = 30

[outputs]
    home = ["HTML", "JSON"]

[author]
    name = "Dominik Schrempf"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "tango"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

# All parameters below here are optional and can be mixed and matched.
[params]
    # Used when a given page doesn't set its own.
    defaultDescription = "Linux, Emacs, coding and more."
    defaultKeywords = "Arch Linux, Emacs, Haskell, C++, Python"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = ""

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/dschrempf"
    bitbucket = ""
    stackOverflow = "https://www.stackoverflow.com/users/3536806"
    linkedin = ""
    googleplus = ""
    facebook = ""
    twitter = "https://twitter.com/fazky"
    youtube = ""
    orcid = "https://orcid.org/0000-0001-8865-9237"
    flattr = ""

    # Mailto link.
    email = "mailto:dominik.schrempf@gmail.com"

    # GPG key.
    gpgkey = "/gpg_public_key.txt"

    # RSS.
    rss = false

    # Privacy statement link.
    privacyPolicy = "/privacy/"

[[menu.main]]
    url = "/linux/"
    name = "Linux"
    weight = 2

[[menu.main]]
    url = "/emacs/"
    name = "Emacs"
    weight = 3

[[menu.main]]
    url = "/coding/"
    name = "Coding"
    weight = 4

[[menu.main]]
    url = "/music/"
    name = "Music"
    weight = 5
