#!/usr/bin/bash

DEST="public"

# Build site.
hugo -d "$DEST"

# Github stuff.
cd "$DEST" || exit
git add .
if [ $# -eq 1 ]; then
    msg="$1"
else
    msg="Rebuilding site $(date)."
fi
git commit -m "$msg"
git push origin master
