#+HUGO_BASE_DIR: ../hugo
#+HUGO_SECTION: ./
#+HUGO_MENU: :menu about :weight 6 :name About
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TYPE: page
#+TITLE: Dominik Schrempf
#+DATE: <2014-12-24 Wed>
#+AUTHOR: Dominik Schrempf
#+EMAIL: dominik.schrempf@gmail.com
#+DESCRIPTION: Personal information.
#+KEYWORDS: "Dominik Schrempf" Blog Linux Emacs Python Haskell "Population Genetics" Music
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+OPTIONS: num:nil

# Gravatar.
#+begin_export html
<img style="border-radius: 50%; float: right;"
     src="https://www.gravatar.com/avatar/b05a00fb86fa378973181afd07c7e548?s=150"
     alt="gravatar"
     title="Dominik Schrempf"/>
<div> Postdoc in Evolutionary Biology<br/>
<a href="https://www.elte.hu/en/">Eötvös Loránd University</a>
</div>
#+end_export

* Interests
- Evolutionary Biology
- Phylogenetics
- Markov Chains
- Functional Programming

* Education
- PhD in Phylogenetics, Vienna University of Veterinary Medicine, 2017
- MSc in Physics, Vienna University of Technology, 2013

* Biography
:PROPERTIES:
:ID:       fcb6959f-90b5-4fa2-aed8-422cb9406d58
:END:
Dominik Schrempf is a postdoc in evolutionary biology at the Eötvös Loránd
University in Budapest. He is developing models suitable for inferring deep
phylogenies, when gene duplication and loss and horizontal gene transfer are
abundant.

During his PhD, Dominik Schrempf worked on phylogenetic models accounting for
present and ancestral genetic variation which leads to incomplete lineage
sorting ([[http://www.iqtree.org/doc/Polymorphism-Aware-Models][PoMo]]). He focused on finding analytical solutions of models in
population genetics to employ in phylogenetic inference. He became particularly
intrigued by the connection between discrete and continuous approaches.

# Maybe insert CV here.

# Maybe link to some talks.

# Maybe link to some other stuff that interests me.

# See https://themes.gohugo.io/theme/academic/.
