#+HUGO_BASE_DIR: ../hugo
#+HUGO_SECTION: ./
#+HUGO_MENU: :menu about :weight 6 :name About
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TYPE: page
#+TITLE: Dominik Schrempf
#+DATE: <2014-12-24 Wed>
#+AUTHOR: Dominik Schrempf
#+EMAIL: dominik.schrempf@gmail.com
#+DESCRIPTION: Personal information
#+KEYWORDS: "Dominik Schrempf" Blog Linux Emacs Python Haskell "Population Genetics" Music
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+OPTIONS: num:nil

# Gravatar.
#+begin_export html
<img style="border-radius: 50%; float: right;"
     src="https://www.gravatar.com/avatar/b05a00fb86fa378973181afd07c7e548?s=150"
     alt="gravatar"
     title="Dominik Schrempf"/>
#+end_export

#+begin_export html
<span class="icons-item"> <a href="https://github.com/dschrempf" target="_blank"><i class="fab fa-github"></i></a></span>
<span class="icons-item"> <a href="https://www.stackoverflow.com/users/3536806" target="_blank"><i class="fab fa-stack-overflow fa-1x"></i></a></span>
<span class="icons-item"> <a rel="me" href="https://fosstodon.org/@dschrempf" target="_blank"><i class="fab fa-mastodon fa-1x"></i></a></span>
<span class="icons-item"> <a href="https://orcid.org/0000-0001-8865-9237" target="_blank"><i class="fab fa-orcid fa-1x"></i></a></span>
<span class="icons-item"> <a href="https://scholar.google.com/citations?user=3pvnGAcAAAAJ" target="_blank"><i class="fab fa-google fa-1x"></i></a></span>
<span class="icons-item"> <a href="mailto:dominik.schrempf@gmail.com"><i class="fas fa-envelope fa-1x"></i></a></span>
<span class="icons-item"> <a href="/gpg_public_key.txt"><i class="fas fa-key fa-1x"></i></a></span>
#+end_export
Haskell software consultant\\
[[https://well-typed.com/][Well-Typed]]

* About
:PROPERTIES:
:ID:       fcb6959f-90b5-4fa2-aed8-422cb9406d58
:END:
With expertise across diverse fields including physics, biology, and web
development, Dominik offers a broad perspective on programming challenges. He
developed a deep affinity for Haskell during his PhD and postdoc years, applying
the language to model evolutionary trees.

This foundational work in Haskell, where the process of building and
manipulating complex structures felt uniquely intuitive and expressive ---
almost like talking directly to the computer --- led him to pursue a career as a
software engineer focused on functional programming. Dominik maintains a set of
Hackage packages geared towards statistical programming. He is also a proficient
user of the Nix language and package manager, with a strong interest in the Nix
ecosystem.

* Interests
- Functional programming (Haskell)
- Software engineering
- Markov chains
- Data science
- Computational biology

* Work experience
- 2025 -- present: Haskell software consultant, Well-Typed (London/Vienna)
- 2023 -- 2025: Software consultant, TNG Technology Consulting (Munich/Vienna)
- 2017 -- 2023:  Postdoc in computational biology (St. Andrews, Budapest)

* Education
- 2013 -- 2017:  PhD in computational biology (Vienna, Aarhus)
- 2006 -- 2013:  BSc and MSc in physics (Vienna, Santiago de Chile)
