#+HUGO_BASE_DIR: ../hugo
#+HUGO_SECTION: ./
#+HUGO_MENU: :menu about :weight 1 :name Links
#+HUGO_AUTO_SET_LASTMOD: t
#+TITLE: Links to newspaper articles
#+DATE: <2018-06-17 Sun>
#+AUTHOR: Dominik Schrempf
#+EMAIL: dominik.schrempf@gmail.com
#+DESCRIPTION: Interesting links.
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+OPTIONS: num:nil

* Deutsch
<2017-11-17 Fri> [[https://derstandard.at/2000067737827/15-000-Forscher-unterstuetzen-dramatische-Warnung-an-die-Menschheit][Appell für Umweltschutz: "Warnung an Menschheit" von 15.000
Forschern]], derStandard. In acht von neun entscheidenden Problemfeldern hat es
seit 1992 Rückschritte gegeben.
   
<2017-11-13 Mon> [[https://derstandard.at/2000067666753/Schriftsteller-Elsberg-ueber-CRISPRCas9-Was-wenn-Gott-sich-geirrt-hat][Schriftsteller Elsberg über CRISPR/Cas9: Was, wenn Gott sich
geirrt hat?]], derStandard. In der postfaktischen Debatte über Gentechnik wird
vermengt, was man auseinanderhalten sollte.
   
<2017-11-06 Mon> [[https://derstandard.at/2000067258484/Es-gibt-zu-viele-Messenger-und-einen-klar-besten-Signal][Es gibt zu viele Messenger – und einen klar besten: Signal]],
derStandard. Nutzer sprechen mittlerweile über dutzende verschiedene Plattformen
miteinander, am klügsten wäre jedoch die Einigung auf Signal.
    
* Español
<2016-09-22 Thu> [[https://elpais.com/cultura/2016/09/15/actualidad/1473939710_796979.html][“A veces, hasta los paranoicos tenemos razón”]], elPaís. Los que
me preocupan son todos esos jóvenes ignorantes que pasan de todo porque dicen
que no tienen nada que ocultar. Es ese tipo de gente que no se preocupa por el
mundo en el que vive, porque se violen los derechos, las libertades que muchos
antes defendieron en la Constitución. Me preocupa la pasividad que veo a mi
alrededor.

<2018-09-04 Tue> [[https://elpais.com/elpais/2018/09/03/ciencia/1535974124_908508.html][El genetista italiano que desmontó el concepto de raza]], elPaís.
“El racismo es un antiguo flagelo de la humanidad”. “Pensamos que la ciencia sea
objetiva. La ciencia está modelada por la sociedad porque es una actividad
humana productiva que necesita tiempo y dinero, pues está guiada y dirigida por
aquellas fuerzas que en el mundo ejercen el control sobre el dinero y sobre el
tiempo. Las fuerzas sociales y económicas determinan en larga medida lo que la
ciencia hace y cómo lo hace”.
