#+HUGO_BASE_DIR: ../../hugo
#+HUGO_SECTION: Music
#+HUGO_TAGS: Music
#+HUGO_TYPE: post
#+TITLE: Cantus Novus Wien
#+DATE: <2015-08-31 Mon>
#+AUTHOR: Dominik Schrempf
#+EMAIL: dominik@schwarzbaer
#+DESCRIPTION: The Cantus Novus Wien is a Viennese choir that I sing in.
#+KEYWORDS: Choir, Cantus Novus, Wien, Vienna, Chor, Klassik, Sakrale Musik
#+LANGUAGE: en

In my free time I love to make music and that's why I am participating
in the choir [[http://www.cantusnovuswien.at/chor][Cantus Novus Wien]].  We are about 40 people and perform
sacred as well as secular music pieces.

* Audio samples

Audio samples can be found on [[https://soundcloud.com/cantusnovuswien][Soundcloud]].

* A short quote from the homepage (in German)
Der Cantus Novus Wien besteht aus engagierten Sängerinnen und Sängern,
die am Wiener Diözesankonservatorium für Kirchenmusik
zusammenfinden. Das gemeinsame, lebendige Singen zielt auf hohe
musikalische Qualität; ein Schwerpunkt ist dabei zeitgenössische
Chormusik mit Uraufführungen von Auftragswerken österreichischer
Komponisten wie Wolfgang Sauseng, Ruth McGuire, Wolfgang Reisinger,
Markus Pfandler und Wolfram Wagner.

Seit einigen Jahren etabliert sich die Zusammenarbeit mit
skandinavischen Künstlern. So gestaltete der Cantus Novus Wien mehrere
Konzerte und CD-Aufnahmen gemeinsam mit Musikern und Komponisten aus
Schweden und Finnland. Eine Erwähnung verdient das Konzert im Wiener
Stephansdom im Mai 2011 gemeinsam mit dem Lidingö Motettkör, dem
Originalchor aus dem schwedischen Kinofilm „Wie im Himmel“. Es folgte
eine Konzertreise nach Stockholm im Juni 2012.

Zum Repertoire zählen auch große, klassische Chorwerke wie Händels
"Israel in Ägypten" und "Messias", Josef Haydns "Schöpfung" und das
"Requiem" von Mozart. Der Cantus Novus Wien gestaltet immer wieder
Gottesdienste, Hochzeiten und kirchliche Veranstaltungen. Regelmäßig
werden Chorreisen für Konzerte mit Chören aus dem In- und Ausland
unternommen.
